---
replicaCount: 1

# This is for database (postgresql) container and can be expanded

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

lisk:
  loglevel: info
  network: testnet
  coldstart: true
  wsPort: 7001
  httpPort: 7000
  api:
    public: true
  database:
    user: lisk
    password: lisk
  image:
    repository: lisk/core
    tag: 1.6.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

postgresql:
  persistence:
    enable: true
    storage: 10Gi
  image:
    repository: postgres
    tag: 10-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1536Mi"
      cpu: "1000m"

redis:
  enabled: true
  image:
    repository: redis
    tag: 5-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "8Mi"
      cpu: "50m"
    limits:
      memory: "16Mi"
      cpu: "100m"
  config:
    maxclients: 8
    tcpbacklog: 128
