---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-lisk-core"
  labels:
    app.kubernetes.io/name: "{{ include "lisk-core.name" . }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lisk-core.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "{{ .Release.Name }}-lisk-core"
  {{- if .Values.postgresql.persistence.enable }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- if .Values.postgresql.persistence.storageClassName }}
        storageClassName: {{ .Values.postgresql.persistence.storageClassName }}
        {{- end }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.storage }}
  {{- end }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "lisk-core.name" . }}"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "lisk-core.name" . }}"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: initdb
          emptyDir: {}
      {{- if .Values.lisk.coldstart }}
      initContainers:
        - name: download-snapshot
          image: busybox
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/postgresql
          command:
            - "/bin/sh"
            - "-c"
            - |
              if [ -f /var/lib/postgresql/pgdata/PG_VERSION ] ; then
                echo "Database already initialized, skipping download."
              else
                wget https://downloads.lisk.io/lisk/{{ .Values.lisk.network }}/blockchain.db.gz -O /docker-entrypoint-initdb.d/00-blockchain.sql.gz
                cat <<EOF > /docker-entrypoint-initdb.d/99-clean-up.sh
              rm /docker-entrypoint-initdb.d/00-blockchain.sql.gz
              EOF
              fi
      {{- end }}
      containers:
        - name: lisk
          image: {{ .Values.lisk.image.repository }}:{{ .Values.lisk.image.tag }}
          resources:
{{ toYaml .Values.lisk.resources | indent 12 }}
          env:
            - name: LISK_DB_USER
              value: {{ .Values.lisk.database.user }}
            - name: LISK_DB_PASSWORD
              value: {{ .Values.lisk.database.password }}
            - name: LISK_DB_NAME
              value: {{ .Values.lisk.network }}
            - name: LISK_CONSOLE_LOG_LEVEL
              value: {{ .Values.lisk.loglevel }}
            - name: LISK_NETWORK
              value: {{ .Values.lisk.network }}
            - name: LISK_WS_PORT
              value: "{{ .Values.lisk.wsPort }}"
            - name: LISK_HTTP_PORT
              value: "{{ .Values.lisk.httpPort }}"
            - name: LISK_API_PUBLIC
              value: "{{ .Values.lisk.api.public }}"
            {{- if .Values.redis.enabled }}
            - name: LISK_CACHE_ENABLED
              value: "true"
            - name: LISK_REDIS_HOST
              value: "localhost"
            - name: LISK_REDIS_PORT
              value: "6379"
            {{- end }}
          command:
            - "/home/lisk/wait-for-it.sh"
            - "-t"
            - "0"
            - "127.0.0.1:5432"
            - "--"
            - "npm"
            - "start"
          ports:
            - name: lisk-core-http
              containerPort: {{ .Values.lisk.httpPort }}
            - name: lisk-core-ws
              containerPort: {{ .Values.lisk.wsPort }}
        - name: database
          image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          {{- $pgConfig := .Values.postgresql.config }}
          {{- $pgMaxmemoryKb := .Values.postgresql.resources.limits.memory| regexFind "[0-9]*" | atoi | mul 1024}}
          {{- $pgSharedBuffers := div $pgMaxmemoryKb 4 }}
          args:
            - "-c"
            - "max_connections={{ $pgConfig.max_connections }}"
            - "-c"
            - "shared_buffers={{ $pgSharedBuffers }}kB"
            - "-c"
            - "work_mem={{ (mul $pgConfig.max_connections 3)|div (sub $pgMaxmemoryKb $pgSharedBuffers) }}kB"
            - "-c"
            - "maintenance_work_mem={{ div $pgMaxmemoryKb 16 }}kB"
            - "-c"
            - "effective_cache_size={{ $pgSharedBuffers }}kB"
            - "-c"
            - "synchronous_commit=off"
            - "-c"
            - "wal_buffers=16MB"
            - "-c"
            - "max_wal_size=2GB"
            - "-c"
            - "min_wal_size=1GB"
            - "-c"
            - "checkpoint_completion_target=0.9"
            - "-c"
            - "default_statistics_target=100"
          resources:
{{ toYaml .Values.postgresql.resources | indent 12 }}
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/postgresql
          env:
            - name: PGDATA
              value: /var/lib/postgresql/pgdata
            - name: POSTGRES_USER
              value: {{ .Values.lisk.database.user }}
            - name: POSTGRES_DB
              value: {{ .Values.lisk.network }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.lisk.database.password }}
        {{- if .Values.redis.enabled }}
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          args:
            - "--maxclients"
            - "{{ .Values.redis.config.maxclients }}"
            - "--tcp-backlog"
            - "{{ .Values.redis.config.tcpbacklog }}"
            - "--maxmemory-policy"
            - "allkeys-lru"
            - "--maxmemory"
            - "{{ lower .Values.redis.resources.limits.memory |replace "i" "b"}}"
            - "--save"
            - ""
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
        {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8}}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8}}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8}}
      {{- end }}
