---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-lisk-core"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-lisk-core"
    helm.sh/chart: {{ include "lisk-core.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: lisk-core-http
      port: {{ .Values.lisk.httpPort }}
      targetPort: lisk-core-http
      protocol: TCP
    - name: lisk-core-ws
      port: {{ .Values.lisk.wsPort }}
      targetPort: lisk-core-ws
      protocol: TCP
    {{- if .Values.redis.monitoring.enabled }}
    - name: redis-metrics
      port: 9121
      targetPort: redis-metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.postgresql.monitoring.enabled }}
    - name: pg-metrics
      port: 9187
      targetPort: pg-metrics
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: "{{ include "lisk-core.name" . }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
