# This file is used by the Makefile.
# You should never need to modify it.
version: '3'
services:
  lisk-task:
    image: lisk/core:${ENV_LISK_VERSION}
    volumes:
      - lisk-data:/home/lisk/.lisk
    entrypoint: /home/lisk/node_modules/.bin/lisk-core
    command: /bin/true
